// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsHy7CPfZQlgMEuzg0upTME2goFuru5K0',
    appId: '1:634594299679:web:25ffcedaa86e158f5faa2a',
    messagingSenderId: '634594299679',
    projectId: 'edu-vista-5d6ba',
    authDomain: 'edu-vista-5d6ba.firebaseapp.com',
    storageBucket: 'edu-vista-5d6ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKiQtWOGaRCNSHf6op4J1lngCr5CKXZFE',
    appId: '1:634594299679:android:7dc55ad84b7689cc5faa2a',
    messagingSenderId: '634594299679',
    projectId: 'edu-vista-5d6ba',
    storageBucket: 'edu-vista-5d6ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChP6V4OIyFSyR3jUCutQT4T0max9Z6_hc',
    appId: '1:634594299679:ios:681a76d968a6efb85faa2a',
    messagingSenderId: '634594299679',
    projectId: 'edu-vista-5d6ba',
    storageBucket: 'edu-vista-5d6ba.appspot.com',
    iosBundleId: 'com.example.eduVista',
  );
}
